#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gera N1 (01_pmids) e N2 (vinculos) do BLOCO02 a partir dos PMIDs do corpus,
com trecho_ancora literal do corpo (regra E3) e schema oficial do Prompt 4.2."""
import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
abs_ = json.loads((BASE / "corpus" / "abstracts_pubmed.json").read_text(encoding="utf-8"))

# chave de citacao -> pmid
KEY2PMID = {
    "Swanson_2019": "31036962", "Bambouskova_2021": "33691097", "CAPS_NLRP3_2024": "38321014",
    "Inflamassomas_estrut_2024": "38374299", "CCR5_NLRP1_2021": "34719258",
    "InnateCellDeath_2022": "35741014", "GSDMD_BBB_2024": "38632402", "TRIM45_2023": "38037161",
    "LPS_cog_2019": "30962497", "Gastrodin_2024": "38552431", "TLR3_2023": "37544956",
    "TLR2_nociceptor_2013": "23965627", "TBK1_2021": "34363755", "S100func_2013": "22834835",
    "HMGB1_HOCl_2024": "38515139", "Omega3_DAMP_2024": "39513898", "miR223_2017": "29144508",
    "InflammAging_2017": "28452964", "IDO1_aging_2022": "35085834", "KYN_gutbrain_2021": "34127024",
    "TNFR1_RIPK1_2021": "34646380", "TNFR2_2025": "40973539", "Arctigenin_2020": "32964428",
    "Bull_2009": "18458677", "Serhan_2014": "24899309", "Serhan_Levy_2018": "29757195",
    "PainResolv_2023": "36859719", "MaR2_2022": "35760872", "GPR37_2018": "30010619",
    "H3K18_2023": "37697347", "Senesc_2022": "35216123", "Punicalin_2024": "38695373",
    "IFN_NSC_2014": "25068123", "Paeoniflorin_2017": "28030814", "IFN_dep_review_2007": "17639827",
    "Fever_2018": "29557255", "COX2_synap_2008": "18537667",
    "cGAS_neuro_2023": "37941028", "cGAS_POCD_2024": "38481801",
    "IL10_struct_2021": "33737461", "IL10_Gal3_2018": "29967195",
    "Klengel_2013": "23201972", "Stress_Epi_2019": "31005627",
    "TNF_suicide_2018": "29361849", "miR146a_2025": "40349816",
    "S100B_2011": "21209080", "S100B_COX2_2007": "17023559", "S100_review_2025": "40867570",
}

# (refid, pmid, desenho, especie_role, achado, extrapol, claim_id, secao)
N1_ROWS = [
 ("REF_Swanson_2019","Swanson_2019","Review (Nat Rev Immunol)","revisao; humano+animal; NLRP3 estrutura/regulacao","preclinical_mechanistic","dois sinais (priming NF-kB; ativacao ASC/caspase-1); IL-1b/IL-18; GSDMD","sim (mecanismo animal; humano por marcador/intervencao)"),
 ("REF_Bambouskova_2021","Bambouskova_2021","Experimental (Cell Rep; camundongo/macrofago)","ML camundongo; itaconato regula sinal 2 do NLRP3","preclinical_mechanistic","itaconato+iNOS estabelecem tolerancia a ativacao tardia do NLRP3 apos priming LPS; dissocia priming de ativacao","sim (camundongo)"),
 ("REF_CAPS_2024","CAPS_NLRP3_2024","Experimental/genetica humana (Nat Commun; pacientes CAPS + modelo)","EC humano+animal; variantes ganho-de-funcao NLRP3","human_clinical","NLRP3 constitutivamente ativo -> clivagem basal de GSDMD, IL-18, piroptose sem gatilho","sim (doenca autoinflamatoria rara -> neuroinflamacao comportamental)"),
 ("REF_Inflamassomas_2024","Inflamassomas_estrut_2024","Review (Nat Rev Immunol)","revisao; estruturas de inflamassomas (NLRP3/NLRP1/AIM2/NLRC4)","preclinical_mechanistic","maquinaria dos inflamassomas; citocinas e piroptose; ligacao a doencas","sim (SNC/comportamento)"),
 ("REF_CCR5_NLRP1_2021","CCR5_NLRP1_2021","Experimental (Stroke; camundongo ICH)","ML camundongo; NLRP1 neuronal","preclinical_mechanistic","CCR5 -> PKA/CREB -> piroptose neuronal dependente de NLRP1 apos hemorragia; maraviroc reduz dano","sim (hemorragia cerebral -> comportamento)"),
 ("REF_InnateCellDeath_2022","InnateCellDeath_2022","Review (Cells)","revisao; morte celular imune na neuroinflamacao/AD","preclinical_mechanistic","morte de microglia/astrocito; AIM2 e piroptose no SNC","sim (AD -> TDM)"),
 ("REF_GSDMD_BBB_2024","GSDMD_BBB_2024","Experimental (Nature; camundongo+scRNA humano)","EC camundongo+humano; GSDMD endotelial","preclinical_mechanistic","caspase-11 sensora de LPS citosolico ativa GSDMD no endotelio cerebral -> ruptura da BHE; LBP-CD14 necessario","sim (sepse/BBB -> comportamento)"),
 ("REF_TRIM45_2023","TRIM45_2023","Experimental (camundongo/celula; encefalopatia septica)","ML camundongo; piroptose microglial","preclinical_mechanistic","TRIM45 agrava piroptose microglial via eixo Atg5/NLRP3","sim"),
 ("REF_LPS_cog_2019","LPS_cog_2019","Experimental (camundongo; LPS i.p.)","ML camundongo; TLR4/NF-kB","preclinical_mechanistic","LPS induz sickness e deficit cognitivo com microglia Iba-1+ e citocinas; via TLR4","sim (modelo agudo)"),
 ("REF_Gastrodin_2024","Gastrodin_2024","Experimental (camundongo; farmacologico)","ML camundongo; TLR4/TRAF6/NF-kB","preclinical_mechanistic","gastrodina reduz neuroinflamacao/ativacao microglial regulando TLR4/TRAF6/NF-kB","sim"),
 ("REF_TLR3_2023","TLR3_2023","Experimental (Signal Transduct Target Ther; camundongo, KO/knockdown)","ML camundongo; TLR3 neuronal hipocampal","preclinical_mechanistic","RNAs extracelulares -> TLR3 hipocampal contribuem para declinio cognitivo na dor cronica; KO/knockdown melhora","sim (dor cronica -> cognicao)"),
 ("REF_TLR2_nociceptor_2013","TLR2_nociceptor_2013","Experimental (Nature; camundongo)","ML camundongo; TLR2/MyD88","preclinical_mechanistic","bacteria ativa nociceptores diretamente; dor nao exige TLR2/MyD88 imune; demonstra ligantes proprios de TLR2","sim"),
 ("REF_TBK1_2021","TBK1_2021","Genetica humana (J Exp Med?; 4 pacientes)","EC humano; perda de TBK1","human_clinical","perda homozigota de TBK1 (integra RLR/cGAS->IFN e NF-kB) causa autoinflamacao cronica por morte TNF; maquinaria de deteccao de RNA/DNA existe","inventario negativo: RLR direto no SNC nao estabelecido"),
 ("REF_S100func_2013","S100func_2013","Review (Curr Mol Med)","revisao; familia S100 (24 membros)","preclinical_mechanistic","S100 com funcoes intra/extracelulares; induziveis em patologia; base do papel DAMP","parcial"),
 ("REF_HMGB1_HOCl_2024","HMGB1_HOCl_2024","Experimental (J Neuroinflammation; rato+humano)","ML rato; HMGB1 microglial","preclinical_mechanistic","HOCl de MPO microglial oxida HMGB1 (dissulfeto) facilitando secrecao e neuroinflamacao na isquemia/reperfusao","sim (isquemia -> TDM)"),
 ("REF_Omega3_DAMP_2024","Omega3_DAMP_2024","Review (Cells; depresao)","revisao; DAMPs na TDM","human_clinical","DAMPs (HMGB1 etc.) disparam ativacao microglial e citocinas na TDM; modulacao lipidica (omega-3)","baixa (revisao translacional)"),
 ("REF_miR223_2017","miR223_2017","Experimental (Cell Death Dis; camundongo/humano)","ML camundongo; DAMP mitocondrial","preclinical_mechanistic","miR-223 de neutrofilos inibe NLRP3 em lesao por DAMP mitocondrial; prova que mtDNA/DAMP mitocondrial gatilha NLRP3","sim (pulmao -> SNC)"),
 ("REF_InflammAging_2017","InflammAging_2017","Review (humano)","revisao; disfuncao mitocondrial/inflamm-aging","human_clinical","disfuncao mitocondrial e vazamento de mtDNA alimentam inflamacao de baixo grau cronica","sim"),
 ("REF_IDO1_aging_2022","IDO1_aging_2022","Review (humano)","revisao; IDO1/quinurenina","preclinical_mechanistic","IDO1 e via da quinurenina regulam imunidade/envelhecimento; enzimas-chave","parcial"),
 ("REF_KYN_gutbrain_2021","KYN_gutbrain_2021","Review (humano+animal)","revisao; triptofano-quinurenina intestino-cerebro","preclinical_mechanistic","metabolismo triptofano->quinurenina como ligacao gut-brain na depressao inflamatoria; bifurcacao KYNA/QUIN","parcial"),
 ("REF_TNFR1_RIPK1_2021","TNFR1_RIPK1_2021","Experimental (camundongo+humano; AD)","ML; necroptose neuronal por TNF","preclinical_mechanistic","necroptose neuronal dependente de TNF-alfa regulada por RIPK1 (via TNFR1)","sim (AD -> TDM)"),
 ("REF_TNFR2_2025","TNFR2_2025","Experimental (camundongo+humano)","ML; TNFR2 microglial","preclinical_mechanistic","sinalizacao TNFR2 molda propriedades remielinizantes/protetoras de microglia apos dano, sexo-dependente","sim"),
 ("REF_Arctigenin_2020","Arctigenin_2020","Experimental (camundongo; modelo de depressao)","ML camundongo","preclinical_mechanistic","arctigenina protege contra depressao inibindo ativacao microglial/neuroinflamacao (reduz TNF)","sim (modelo depressivo)"),
 ("REF_Bull_2009","Bull_2009","Genetica funcional humana (Mol Psychiatry; hepatite C/IFN)","EC humano; interacao gene-ambiente","human_clinical","polimorfismos funcionais IL-6 (rs1800795/-174) e 5-HTTLPR modificam depressao induzida por IFN-alfa; variantes hiper-IL6 -> mais risco","baixa (humano direto)"),
 ("REF_Serhan_2014","Serhan_2014","Review (Nature)","revisao; SPMs","preclinical_mechanistic","SPMs (resolvinas/protectinas/maresinas/lipoxinas) medeiam resolucao ativa (para neutrofilos, eferocitose)","sim (fisiologia -> psiquiatria)"),
 ("REF_Serhan_Levy_2018","Serhan_Levy_2018","Review (J Clin Invest)","revisao; resolvinas","preclinical_mechanistic","superfamilia das resolvinas: receptores e acoes pro-resolucao","sim"),
 ("REF_PainResolv_2023","PainResolv_2023","Review (dor neuropatica)","revisao; mecanismos pro-resolutivos","preclinical_mechanistic","mecanismos imunes de resolucao da dor como alvo; SPMs e eferocitose","sim"),
 ("REF_MaR2_2022","MaR2_2022","Experimental (camundongo)","ML; maresina","preclinical_mechanistic","MaR2 derivada de tecido adiposo marrom contribui para resolucao da inflamacao no frio","sim"),
 ("REF_GPR37_2018","GPR37_2018","Experimental (camundongo+humano)","ML; GPR37 macrofago","preclinical_mechanistic","GPR37 regula fagocitose macrofagica e resolucao da dor inflamatoria","sim"),
 ("REF_H3K18_2023","H3K18_2023","Experimental (camundongo+humano; microglia senescente)","ML; lactilacao de histona","preclinical_mechanistic","lactilacao H3K18 em microglia senescente potencializa SASP e envelhecimento cerebral/AD","sim (AD/envelhecimento -> TDM)"),
 ("REF_Senesc_2022","Senesc_2022","Review","revisao; senescencia celular","preclinical_mechanistic","senescencia celular e SASP como mecanismo de neuroinflamacao cronica","sim"),
 ("REF_Punicalin_2024","Punicalin_2024","Experimental (camundongo; LPS)","ML; NF-kB","preclinical_mechanistic","punicalina atenua prejuizo de memoria/comportamento induzido por LPS suprimindo cascata NF-kB","sim"),
 ("REF_IFN_NSC_2014","IFN_NSC_2014","Experimental/Review (celula; NSC)","ML celula; IFN-alfa","preclinical_mechanistic","mecanismos da depressao induzida por IFN-alfa e disfuncao de celulas-tronco neurais; JAK-STAT/IDO","sim (modelo do paradigma humano)"),
 ("REF_Paeoniflorin_2017","Paeoniflorin_2017","Experimental (camundongo; IFN-alfa)","ML camundongo","preclinical_mechanistic","paeoniflorina alivia neuroinflamacao e comportamento tipo-depressivo induzidos por IFN-alfa","sim"),
 ("REF_IFN_dep_review_2007","IFN_dep_review_2007","Review (humano; hepatite C)","revisao clinica","human_clinical","depressao induzida por interferon: mecanismos e manejo; paradigma causal humano","baixa"),
 ("REF_Fever_2018","Fever_2018","Review (humano+animal)","revisao; febre/PGE2","preclinical_mechanistic","mecanismos neurais da febre induzida por inflamacao; PGE2 hipotalamico; receptores EP","parcial"),
 ("REF_COX2_synap_2008","COX2_synap_2008","Review","revisao; COX-2 sinaptica","preclinical_mechanistic","COX-2 tem papel em sinalizacao sinaptica alem da inflamacao","parcial"),
 ("REF_cGAS_neuro_2023","cGAS_neuro_2023","Review (humano; doencas neurologicas)","revisao; cGAS-STING","preclinical_mechanistic","cGAS detecta DNA citosolico (mtDNA) -> cGAMP -> STING -> TBK1/IRF3 -> IFN-I + NF-kB no SNC","sim"),
 ("REF_cGAS_POCD_2024","cGAS_POCD_2024","Experimental (camundongo; sevoflurano)","ML camundongo","preclinical_mechanistic","eixo mtDNA-cGAS-STING ativa NLRP3 microglial na disfuncao cognitiva pos-operatoria","sim"),
 ("REF_IL10_struct_2021","IL10_struct_2021","Experimental estrutural (Science; humano+camundongo)","EC; IL-10R","preclinical_mechanistic","estrutura do complexo IL-10/IL-10Ra/b; desacopla funcoes pro/anti-inflamatorias; limiares STAT3 por celula","parcial"),
 ("REF_IL10_Gal3_2018","IL10_Gal3_2018","Experimental (camundongo)","ML; IL-10-STAT3","preclinical_mechanistic","eixo IL-10-STAT3-galectina-3 essencial para macrofagos reparativos; freio anti-inflamatorio","sim"),
 ("REF_Klengel_2013","Klengel_2013","Genetica/epigenetica humana (Nat Neurosci)","EC humano; FKBP5","human_clinical","polimorfismo FKBP5 + trauma infantil -> desmetilacao alelo-especifica dependente de trauma -> risco psiquiatrico adulto; resistencia a GR","baixa (humano direto)"),
 ("REF_Stress_Epi_2019","Stress_Epi_2019","Revisao sistematica (Neurosci Biobehav Rev; humano)","revisao sistematica humano","human_clinical","mudancas epigeneticas por estresse (NR3C1, FKBP5, BDNF...) correlacionadas com depressao (17 estudos)","baixa"),
 ("REF_TNF_suicide_2018","TNF_suicide_2018","Post-mortem humano (Am J Psychiatry)","EC post-mortem; PFC suicidio","post_mortem","chaveamento epigenetico complexo (microRNA/proteina ligadora de RNA) causa superexpressao de TNF-alfa no CPF dl de suicidas","baixa (humano post-mortem)"),
 ("REF_miR146a_2025","miR146a_2025","Experimental (Exp Neurol; camundongo)","ML camundongo; miR-146a","preclinical_mechanistic","superexpressao de miR-146a em microglia hipocampal melhora cognicao via IRAK1/TRAF6/NF-kB; freio pos-transcricional","sim"),
 ("REF_S100B_2011","S100B_2011","Experimental (J Biol Chem; camundongo/rato)","ML; S100B/RAGE","preclinical_mechanistic","S100B alto estimula migracao microglial via RAGE com upregulacao de quimiocinas; concentracoes fisiologicas sao troficas","parcial"),
 ("REF_S100B_COX2_2007","S100B_COX2_2007","Experimental (J Leukoc Biol; camundongo/humano)","ML; S100B/RAGE","preclinical_mechanistic","ligacao S100B-RAGE em microglia estimula COX-2; alta concentracao + LPS/IFN-g induz iNOS/NO; efeito dual dose","parcial"),
 ("REF_S100_review_2025","S100_review_2025","Review (Biomolecules)","revisao; S100/SNC","preclinical_mechanistic","S100B e S100A8/A9 como DAMPs via RAGE/TLR disparam glia/pro-inflamatorios; baixas concentracoes podem ser neuroprotetoras","parcial"),
]

n1 = []
for refid, key, desenho, papel, role, achado, extrapol in N1_ROWS:
    pmid = KEY2PMID[key]
    r = abs_[pmid]
    n1.append({
        "id_referencia_interna": refid,
        "pmid_oficial": pmid,
        "doi": r["doi"],
        "titulo_artigo": r["titulo"],
        "autores": r["autores"][:6],
        "revista_ano": f"{r['revista']} ({r['ano']})",
        "desenho_estudo": desenho,
        "secao_origem": "mecanismo_B1_neuroinflamacao/BLOCO_02",
        "achado_central_molecular": achado,
        "extrapolacao_por_analogia": extrapol,
        "status_auditoria": "",
        "claim_id_origem": "",
        "citacao_confirmada": True,
        "origem_pipeline": "BUSCA_FERRAMENTA",
        "g1_metodo": "eutils_automatico",
        "g3_verificado_por": "",
        "especie_mesh": r["especie_mesh"],
        "evid_role": role,
        "verification_status": "pendente",
    })

# N2: (refid, claim_id, secao, trecho literal, natureza, maturidade, forca, extrapol, role, uso)
N2 = [
 ("REF_Swanson_2019","B1.MEC.BLOCO02.001","BLOCO_02/2.1",
  "Sua ativação exige dois sinais: o sinal 1 (priming) — TLR4/TNFR/IL-1R → NF-κB — induz a transcrição de NLRP3 e da pró-IL-1β; o sinal 2 (ativação) — disparado por ATP/P2X7, dano mitocondrial (mtROS, mtDNA), eflixo de K+ ou cristais — promove a montagem do complexo NLRP3–ASC–pró-caspase-1, com autoclivagem da caspase-1 e maturação de IL-1β/IL-18 e clivagem de GSDMD (Swanson et al., 2019)[OB; revisão, humano+animal].",
  "causal","bem_suportado","","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Bambouskova_2021","B1.MEC.BLOCO02.001","BLOCO_02/2.1",
  "A dependência de dois sinais é explorada fisiologicamente como tolerância: em macrófagos, o itaconato induzido por TLR regula o sinal 2 após priming prolongado por LPS, estabelecendo tolerância à ativação tardia do NLRP3 em sinergia com iNOS — demonstração manipulável de que priming e ativação são etapas dissociáveis (Bambouskova et al., 2021)[ML; camundongo].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","sim (camundongo)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_CAPS_2024","B1.MEC.BLOCO02.001","BLOCO_02/2.1",
  "A prova de que a montagem do complexo é necessária e suficiente vem da genética humana: variantes ganho-de-função de NLRP3 (síndromes cryopyrin/CAPS) formam inflamassomas constitutivamente ativos, com clivagem basal de gasdermina D, liberação de IL-18 e piroptose mesmo sem gatilho externo — em pacientes e modelos animais (Heneka/Swanson linhas; Pathogenic NLRP3 mutants, 2024)[EC; humano+camundongo][EXT para TDM].",
  "causal","bem_suportado","tier_1_necessidade_e_suficiencia","sim (doenca rara -> TDM)","human_clinical","contexto_mecanistico"),
 ("REF_Inflamassomas_2024","B1.MEC.BLOCO02.002","BLOCO_02/2.2",
  "Os inflamassomas são complexos supramoleculares citosólicos que respondem a PAMPs/DAMPs e desencadeiam liberação de citocinas e piroptose; a família inclui NLRP3, NLRP1, AIM2 (sensor de DNA) e NLRC4, com estruturas e ligantes distintos (Mechanistic insights from inflammasome structures, 2024)[OB; revisão, humano+animal].",
  "associativa","bem_suportado","","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_CCR5_NLRP1_2021","B1.MEC.BLOCO02.002","BLOCO_02/2.2",
  "No parênquima cerebral, há evidência direta de via análoga para NLRP1 em neurônios: após hemorragia intracerebral experimental, a ativação de CCR5 promove piroptose neuronal dependente de NLRP1 via CCR5/PKA/CREB, e o antagonismo de CCR5 (maraviroc) reduz o dano (CCR5/NLRP1 neuronal pyroptosis, 2021)[ML; camundongo][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim (camundongo)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_InnateCellDeath_2022","B1.MEC.BLOCO02.002","BLOCO_02/2.2",
  "AIM2 aparece como sensor de DNA em contexto de morte celular imune na neuroinflamação (Innate Immune Cell Death in Neuroinflammation, 2022)[OB; revisão][EXT]; NLRC4 tem evidência indireta.",
  "associativa","hipotese_inicial","","sim","preclinical_mechanistic","gap_pesquisa"),
 ("REF_GSDMD_BBB_2024","B1.MEC.BLOCO02.003","BLOCO_02/2.3",
  "Demonstração recente e forte no SNC: a ativação de GSDMD no endotélio cerebral — pela caspase-11 sensora de LPS citosólico, e não pelas citocinas induzidas por TLR4 — medeia a ruptura inflamatória da barreira hematoencefálica na sepse/desafio com LPS circulante; camundongos deficientes na via LBP–CD14 de internalização de LPS resistem à quebra da barreira (Brain endothelial GSDMD activation mediates inflammatory BBB breakdown, 2024)[EC; camundongo+humano][EXT].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","sim (sepse -> comportamento)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TRIM45_2023","B1.MEC.BLOCO02.003","BLOCO_02/2.3",
  "Em microglia, GSDMD medeia piroptose na encefalopatia séptica via eixo TRIM45/Atg5/NLRP3 (TRIM45 microglia pyroptosis, 2023)[ML; camundongo][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_LPS_cog_2019","B1.MEC.BLOCO02.004","BLOCO_02/2.4",
  "A via completa — LPS → TLR4/MyD88 → IRAK/TRAF6 → IKK → degradação de IκBα → NF-κB nuclear → transcrição de IL1B/IL6/TNF — é demonstrada por manipulação: o desafio com LPS induz sickness, déficit cognitivo e ativação microglial (Iba-1+) em camundongos, com elevação de citocinas pró-inflamatórias, bloqueável por interferência na via (LPS-induced cognitive impairment in mice, 2019)[ML; camundongo].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","sim (camundongo)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Gastrodin_2024","B1.MEC.BLOCO02.004","BLOCO_02/2.4",
  "A modulação farmacológica a jusante confirma os elos: gastrodina reduz neuroinflamação e ativação microglial regulando TLR4/TRAF6/NF-κB (Gastrodin TLR4/TRAF6/NF-κB, 2024)[ML; camundongo][EXT].",
  "causal","moderadamente_suportado","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TLR3_2023","B1.MEC.BLOCO02.005","BLOCO_02/2.5",
  "TLR3 neuronal é relevante para função cognitiva: em camundongos com dor neuropática crônica, RNAs extracelulares sinalizam via TLR3 no hipocampo e contribuem para o declínio cognitivo; o knockout de TLR3 e o knockdown neuronal específico melhoram a cognição, reduzem citocinas e apoptose neuronal versus selvagens (Extracellular RNAs–TLR3 cognitive impairment, 2023)[ML; camundongo][EXT].",
  "causal","moderadamente_suportado","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TLR2_nociceptor_2013","B1.MEC.BLOCO02.005","BLOCO_02/2.5",
  "TLR2 media resposta imune a bactéria em nociceptores de forma distinta da via glial (Bacteria activate sensory neurons, 2013)[ML; camundongo].",
  "contributiva","moderadamente_suportado","","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TBK1_2021","B1.MEC.BLOCO02.006","BLOCO_02/2.6",
  "O que existe é periférico: TBK1 — que integra a sinalização de RLRs e cGAS-STING para IFN tipo I e NF-κB — quando perdido em humanos por mutações homozigotas causa autoinflamação crônica sistêmica dirigida por morte celular induzida por TNF, sem infecções virais graves (Human TBK1 deficiency autoinflammation, 2021)[EC; humano].",
  "nao_estabelecida","hipotese_inicial","","inventario negativo (RLR direto no SNC nao localizado)","human_clinical","gap_pesquisa"),
 ("REF_HMGB1_HOCl_2024","B1.MEC.BLOCO02.008","BLOCO_02/2.8",
  "Em lesão cerebral isquêmica, ácido hipocloroso derivado de mieloperoxidase microglial oxida HMGB1 facilitando sua secreção e amplificando a neuroinflamação (HOCl microglial MPO → HMGB1 release, 2024)[ML; rato+humano][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Omega3_DAMP_2024","B1.MEC.BLOCO02.008","BLOCO_02/2.8",
  "Em revisão focada em depressão, DAMPs (incluindo HMGB1) são apresentados como alarmes que disparam ativação microglial e liberação de citocinas na TDM, com modulação lipídica (Omega-3/DAMPs in depression, 2024)[OB; revisão, humano+animal].",
  "associativa","emergente","","sim (revisao translacional)","human_clinical","contexto_mecanistico"),
 ("REF_miR223_2017","B1.MEC.BLOCO02.009","BLOCO_02/2.9",
  "Em lesão pulmonar aguda induzida por DAMP mitocondrial, miR-223 de neutrófilos Ly6G+ inibe o NLRP3 — demonstrando que DAMPs mitocondriais são gatilho fisiológico do complexo (miR-223 inhibits NLRP3 in mitochondrial DAMP injury, 2017)[ML; camundongo][EXT].",
  "causal","moderadamente_suportado","tier_2_necessidade_ou_suficiencia","sim (pulmao -> SNC)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_InflammAging_2017","B1.MEC.BLOCO02.009","BLOCO_02/2.9",
  "A disfunção mitocondrial e o \"inflamm-aging\" são alimentados por vazamento de mtDNA e sinalização imune (Fueling Inflamm-Aging through Mitochondrial Dysfunction, 2017)[OB; revisão, humano].",
  "contributiva","bem_suportado","","parcial","human_clinical","contexto_mecanistico"),
 ("REF_KYN_gutbrain_2021","B1.MEC.BLOCO02.010","BLOCO_02/2.10",
  "A bifurcação celular é funcionalmente oposta: em astrócitos, KAT (kynurenine aminotransferase) gera KYNA (ácido quinurênico) — antagonista NMDA no sítio glicina/agonista α7nACh, neuroprotetor; em micróglia/macrófagos, KMO direciona para QUIN (ácido quinolínico) e 3-HK — agonista NMDA, gerador de ROS, neurotóxico.",
  "causal","muito_estabelecido","","baixa (bioquimica conservada)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_IDO1_aging_2022","B1.MEC.BLOCO02.010","BLOCO_02/2.10",
  "O triptofano é desviado da serotonina para a via da quinurenina por ação de IDO1 (induzida por citocinas/IFN-γ), IDO2 e TDO2.",
  "contributiva","bem_suportado","","parcial","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TNFR1_RIPK1_2021","B1.MEC.BLOCO02.011","BLOCO_02/2.11",
  "Em modelo de Alzheimer, a necroptose neuronal dependente de TNF-α é regulada pela coordenação RIPK1 (TNF-α neuronal necroptosis RIPK1, 2021)[ML; camundongo+humano][EXT].",
  "causal","moderadamente_suportado","tier_2_necessidade_ou_suficiencia","sim (AD -> TDM)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_TNFR2_2025","B1.MEC.BLOCO02.011","BLOCO_02/2.11",
  "Ao contrário, TNFR2 em microglia molda propriedades remielinizantes e protetoras após dano, de forma sexo-dependente (TNFR2 microglia remyelination, 2025)[ML; camundongo+humano][EXT].",
  "compensatoria","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Arctigenin_2020","B1.MEC.BLOCO02.011","BLOCO_02/2.11",
  "Em modelo de depressão induzida, a inibição de microglia/neuroinflamação por arctigenina envolve a redução de TNF (Arctigenin anti-depression microglia, 2020)[ML; camundongo].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim (modelo depressivo)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Bull_2009","B1.MEC.BLOCO02.012","BLOCO_02/2.12",
  "O achado mais diretamente ancorado nesta trilha: polimorfismos funcionais em IL-6 (rs1800795/-174G>C) e no transportador de serotonina (5-HTTLPR) modificam a depressão induzida por interferon-α em hepatite C — variantes que elevam sinalização IL-6 associam-se a maior risco de depressão sob terapia com citocina (Bull et al., 2009)[EC; humano].",
  "causal","bem_suportado","tier_3_correlacional_mecanistico","baixa (humano direto; interacao gene-ambiente)","human_clinical","clinico"),
 ("REF_Serhan_2014","B1.MEC.BLOCO02.013","BLOCO_02/2.13",
  "Mediadores lipídicos especializados — resolvinas (da série E de EPA e D de DHA), protectinas/PD1/NPD1, maresinas (MaR), lipoxina A4 (do araquidônico) — produzidos por lipoxigenases, param o recrutamento neutrofílico, promovem eferocitose e retornam tecidos à homeostase (Serhan, 2014)[OB; revisão, humano+animal]; a superfamília das resolvinas é detalhada quanto a receptores e ações (Serhan & Levy, 2018)[OB; revisão].",
  "causal","bem_suportado","","sim (fisiologia -> psiquiatria)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_PainResolv_2023","B1.MEC.BLOCO02.013","BLOCO_02/2.13",
  "Em dor neuropática, mecanismos imunes pró-resolutivos são mapeados como alvo terapêutico (Pain-resolving immune mechanisms, 2023)[OB; revisão], e a maresina MaR2 derivada de tecido adiposo marrom contribui para a resolução da inflamação no frio (Brown adipose MaR2 resolution, 2022)[ML; camundongo][EXT].",
  "contributiva","emergente","","sim","preclinical_mechanistic","gap_pesquisa"),
 ("REF_GPR37_2018","B1.MEC.BLOCO02.013","BLOCO_02/2.13",
  "O GPR37 em macrófagos regula fagocitose e resolução da dor inflamatória (GPR37 macrophage phagocytosis resolution, 2018)[ML; camundongo+humano][EXT].",
  "contributiva","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_H3K18_2023","B1.MEC.BLOCO02.014","BLOCO_02/2.14",
  "Em microglia senescente no envelhecimento/Alzheimer, a lactilação de histona H3K18 potencializa o SASP e o declínio cerebral (H3K18 lactylation of senescent microglia, 2023)[ML; camundongo+humano][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim (envelhecimento/AD -> TDM)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Senesc_2022","B1.MEC.BLOCO02.014","BLOCO_02/2.14",
  "O envelhecimento celular e a senescência estão consolidados como mecanismo de neuroinflamação crônica (Aging, Cellular Senescence and Alzheimer's, 2022)[OB; revisão].",
  "contributiva","bem_suportado","","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Gastrodin_2024","B1.MEC.BLOCO02.015","BLOCO_02/2.15",
  "Sequência: receptor (TLR4/MyD88, TNFR1 ou IL-1R1) → IRAK/TRAF6 → complexo IKK → fosforilação e degradação de IκBα → libertação e translocação nuclear de NF-κB (p65/p50) → transcrição de IL1B, IL6, TNF, NLRP3 (priming), PTGS2 (COX-2) e NOS2 (iNOS).",
  "causal","muito_estabelecido","","baixa (bioquimica conservada)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Punicalin_2024","B1.MEC.BLOCO02.015","BLOCO_02/2.15",
  "A via é confirmada por manipulação em microglia: gastrodina reduz neuroinflamação agindo em TLR4/TRAF6/NF-κB (Gastrodin TLR4/TRAF6/NF-κB, 2024)[ML; camundongo], e o polifenol punicalina atenua prejuízo de memória induzido por LPS por supressão da mesma cascata (Punicalin LPS memory NF-κB, 2024)[ML; camundongo][EXT].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_IFN_NSC_2014","B1.MEC.BLOCO02.016","BLOCO_02/2.16",
  "IFN tipo I (IFN-α/β via IFNAR) e tipo II (IFN-γ via IFNGR) sinalizam por JAK1/JAK2/TYK2 → STAT1/STAT2 → genes estimulados por IFN (ISGs), incluindo indução de IDO1 (2.10).",
  "causal","muito_estabelecido","","baixa","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_IFN_dep_review_2007","B1.MEC.BLOCO02.016","BLOCO_02/2.16",
  "O paradigma de causalidade humana mais próximo de B1 é a depressão induzida por interferon-α: pacientes tratados com IFN-α (hepatite C/melanoma) desenvolvem sintomas depressivos de novo com curso previsível, e a maquinaria JAK-STAT/IDO está documentada em células-tronco neurais (Mechanisms for IFN-α-induced depression and NSC dysfunction, 2014)[ML; célula+revisão]; um composto natural (paeoniflorin) alivia neuroinflamação e comportamento tipo-depressivo induzidos por IFN-α (Paeoniflorin IFN-α depression, 2017)[ML; camundongo][EXT], e trans-cinamaldeído restaura a função astrocitária no mesmo modelo (Trans-cinnamaldehyde IFN-α astrocyte, 2025)[ML; camundongo].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","baixa (humano: intervencao exogena; ML animal)","human_experimental","clinico"),
 ("REF_Fever_2018","B1.MEC.BLOCO02.017","BLOCO_02/2.17",
  "A inflamação induz COX-2 (PTGS2, transcrito de NF-κB), que gera PGE2 do araquidônico. PGE2 sinaliza pelos receptores EP1–EP4 e é o mediador central da febre e de parte do sickness: os mecanismos neurais da febre induzida por inflamação, com PGE2 hipotalâmico à frente, estão detalhados (Neural Mechanisms of Inflammation-Induced Fever, 2018)[OB; revisão, humano+animal].",
  "causal","bem_suportado","","parcial","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_COX2_synap_2008","B1.MEC.BLOCO02.017","BLOCO_02/2.17",
  "COX-2 também tem papel em sinalização sináptica (Cyclooxygenase-2 in synaptic signaling, 2008)[OB; revisão, humano+animal].",
  "associativa","bem_suportado","","parcial","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_cGAS_neuro_2023","B1.MEC.BLOCO02.018","BLOCO_02/2.18",
  "DNA ectópico no citosol (mtDNA vazando, DNA nuclear dano) é detectado por cGAS, que produz cGAMP; cGAMP ativa STING → TBK1 → IRF3 → IFN tipo I, além de NF-κB. A via está consolidada como mecanismo de neuroinflamação em doenças neurológicas (cGAS-STING in neurological disorders, 2023)[OB; revisão, humano]; o cruzamento mitofagia–cGAS-STING é revisado na neuroinflamação (Mitophagy and cGAS-STING crosstalk, 2024)[OB].",
  "causal","bem_suportado","","sim (doencas neurologicas -> TDM)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_cGAS_POCD_2024","B1.MEC.BLOCO02.018","BLOCO_02/2.18",
  "Há prova manipulável no SNC: na disfunção cognitiva pós-operatória por sevoflurano, a ativação do NLRP3 dependente do eixo mtDNA–cGAS-STING em microglia conduz a neuroinflamação (mtDNA-cGAS-STING–NLRP3 postoperative cognition, 2024)[ML; camundongo][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_IL10_struct_2021","B1.MEC.BLOCO02.019","BLOCO_02/2.19",
  "IL-10 liga IL-10Rα + IL-10Rβ (receptor compartilhado) e sinaliza por JAK1/TYK2 → STAT3, suprimindo transcrição pró-inflamatória. A biologia estrutural recente desacoplou as funções pró e anti-inflamatórias da IL-10 e mostrou limiares distintos entre populações imunes (Structure-based decoupling of IL-10 functions, 2021)[EC; humano+camundongo].",
  "compensatoria","bem_suportado","tier_2_necessidade_ou_suficiencia","parcial","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_IL10_Gal3_2018","B1.MEC.BLOCO02.019","BLOCO_02/2.19",
  "O eixo IL-10–STAT3–galectina-3 é essencial para macrófagos reparativos (IL-10-STAT3-Galectin-3 reparative macrophages, 2018)[ML; camundongo], e a entrega direcionada de IL-10 a microglia/macrófago melhora desfecho em hemorragia intracerebral (microglia-targeted IL-10 ICH, 2023)[ML; camundongo][EXT].",
  "compensatoria","bem_suportado","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_Klengel_2013","B1.MEC.BLOCO02.020","BLOCO_02/2.20",
  "O achado humano seminal: um polimorfismo funcional em FKBP5 (regulador do receptor de glicocorticoide) altera a interação da cromatina entre o sítio de início de transcrição e enhancers de longo alcance, e produz desmetilação alelo-específica dependente de trauma de infância em elementos de resposta a glicocorticoide, aumentando o risco de transtorno psiquiátrico relacionado ao estresse no adulto (Klengel et al., 2013)[EC; humano].",
  "causal","muito_estabelecido","tier_3_correlacional_mecanistico","baixa (humano direto)","human_clinical","clinico"),
 ("REF_Stress_Epi_2019","B1.MEC.BLOCO02.020","BLOCO_02/2.20",
  "A revisão sistemática do estresse/epigenética/depressão consolida NR3C1 (metilação do promotor do GR), FKBP5, BDNF e outros genes correlacionados com depressão (Stress, epigenetics and depression: systematic review, 2019)[OB; revisão sistemática, humano].",
  "associativa","bem_suportado","tier_3_correlacional_mecanistico","baixa (humano)","human_clinical","clinico"),
 ("REF_TNF_suicide_2018","B1.MEC.BLOCO02.021","BLOCO_02/2.21",
  "Em cérebro humano pós-morte, a regulação da expressão de TNF-α envolve chaveamento epigenético complexo: no córtex pré-frontal de indivíduos que morreram por suicídio, a superexpressão de TNF-α é explicada por mecanismos de microRNA e proteína de ligação a RNA que destravam o gene (Complex Epigenetic Switching in TNF-α Upregulation in suicide PFC, 2018)[EC; post-mortem humano].",
  "contributiva","moderadamente_suportado","tier_3_correlacional_mecanistico","baixa (humano post-mortem)","post_mortem","contexto_mecanistico"),
 ("REF_miR146a_2025","B1.MEC.BLOCO02.022","BLOCO_02/2.22",
  "miR-146a é o freio: tem como alvos IRAK1/TRAF6, e sua superexpressão em microglia hipocampal melhora função cognitiva reduzindo a via IRAK1/TRAF6/NF-κB (miR-146a hippocampal microglia IRAK1/TRAF6, 2025)[ML; camundongo]; vesículas extracelulares enriquecidas em miR-146a têm efeito imunomodulador/neuroprotetor (miR-146a-enriched MSC EV, 2025)[EC; célula/camundongo/humano], e miR-146a-5p reduz neuroinflamação em outros modelos [ML].",
  "compensatoria","emergente","tier_2_necessidade_ou_suficiencia","sim (camundongo)","preclinical_mechanistic","gap_pesquisa"),
 ("REF_H3K18_2023","B1.MEC.BLOCO02.023","BLOCO_02/2.23",
  "Em microglia senescente, a lactilação de H3K18 mantém o programa transcricional pró-inflamatório no envelhecimento/Alzheimer (H3K18 lactylation senescent microglia, 2023)[ML; camundongo+humano][EXT].",
  "causal","emergente","tier_2_necessidade_ou_suficiencia","sim","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_S100B_2011","B1.MEC.BLOCO02.024","BLOCO_02/2.24",
  "Têm efeito dual por concentração e afinidade de receptor: em níveis fisiológicos (nanomolar), S100B é trófico para neurônios; em níveis altos (micromolar), liberados por astrócitos lesados, S100B age via RAGE e é pró-inflamatório/tóxico (S100B stimulates microglia migration via RAGE chemokines, 2011)[ML; camundongo/rato]; a ligação S100B–RAGE em microglia estimula expressão de COX-2 e, em alta concentração, iNOS/NO em sinergia com LPS/IFN-γ (S100B–RAGE microglia COX-2, 2007)[ML; camundongo/humano].",
  "causal","bem_suportado","tier_2_necessidade_ou_suficiencia","parcial (animal/celula)","preclinical_mechanistic","contexto_mecanistico"),
 ("REF_S100_review_2025","B1.MEC.BLOCO02.024","BLOCO_02/2.24",
  "A revisão de 2025 consolida S100B e S100A8/A9 como DAMPs que interagem com RAGE/TLRs disparando cascatas pró-inflamatórias e ativação glial, com nota explícita de que concentrações baixas podem ser neuroprotetoras (Relationship of S100 Proteins with Neuroinflammation, 2025)[OB; revisão, humano+animal].",
  "associativa","bem_suportado","","parcial","preclinical_mechanistic","contexto_mecanistico"),
]

n2 = []
for i, (refid, claim, secao, trecho, nat, mat, forca, extrapol, role, uso) in enumerate(N2, 1):
    n2.append({
        "id_vinculo": f"VINC_B1_{1000+i:04d}",
        "id_referencia_interna": refid,
        "claim_id": claim,
        "mecanismo_origem": "B1",
        "secao_origem": secao,
        "trecho_ancora": trecho,
        "achado_central_molecular": next(r["achado_central_molecular"] for r in n1 if r["id_referencia_interna"]==refid),
        "natureza_relacao": nat,
        "grau_maturidade": mat,
        "forca_causal": forca,
        "extrapolacao_por_analogia": extrapol,
        "evid_role": role,
        "uso": uso,
        "status_referencia": "CANDIDATO",
        "status_auditoria": "",
        "verification_status": "pendente",
        "data_verificacao": "",
        "g2_elegibilidade": "nao_avaliado",
        "g2_motivo": "",
        "g1_metodo": "eutils_automatico",
        "g3_verificado_por": "",
    })

out = BASE / "ato2_pacote"
(out / "mod9_BLOCO02_N1_01_pmids.json").write_text(json.dumps(n1, ensure_ascii=False, indent=1), encoding="utf-8")
(out / "mod9_BLOCO02_N2_vinculos.json").write_text(json.dumps(n2, ensure_ascii=False, indent=1), encoding="utf-8")
print("N1:", len(n1), "refs | N2:", len(n2), "vinculos")
# validacao E3 e integridade
ids1 = {r["id_referencia_interna"] for r in n1}
prob = []
for v in n2:
    if v["trecho_ancora"].rstrip()[-1] not in '.!?]': prob.append(("PONT", v["id_vinculo"]))
    if v["id_referencia_interna"] not in ids1: prob.append(("REF", v["id_vinculo"]))
    if v["g3_verificado_por"] != "": prob.append(("G3", v["id_vinculo"]))
for r in n1:
    if r["pmid_oficial"] not in abs_: prob.append(("PMID", r["pmid_oficial"]))
print("problemas:", prob if prob else "NENHUM")
