# -*- coding: utf-8 -*-
# Tabela-mestra das 76 refs ENTRA da rodada [AT] GPM B9 2026-09-09 (aprovada pelo usuário: completo 76).
# Campos: (rid, pmid, prosa, tag, bloco, nn, erole, mat, desenho, g2m, achado, alx)
#   tag        = OB revisão/conceitual | EC humano | ML pré-clínico (roedor/célula)
#   bloco/nn   = claim_id_origem  B9.MEC.<bloco>.<nn>
#   erole      = evid_role
#   mat        = grau_maturidade (oficial): bem_suportado | moderadamente_suportado | emergente
#   alx        = aliases extras (diacríticos/compostos)

D = [
# ================= BLOCO_01 §1.1 OXPHOS/células humanas =================
('REF_ALLEN_2018','29928190','Allen 2018','OB','BLOCO01',1,'review','bem_suportado',
 'revisão integradora (Front Neurosci)','revisão-âncora "Mitochondria and Mood" — master do insumo, não do molde',
 'A disfunção mitocondrial é revisada como peça-chave da manifestação depressiva — enquadramento integrador, não prova causal humana.',[]),
('REF_TRIEBELHORN_2024','35732695','Triebelhorn 2024','EC','BLOCO01',2,'human_experimental','bem_suportado',
 'células progenitoras neurais induzidas e neurônios iPS de pacientes com TDM','briefing dizia "não localizado" — é 35732695 (Mol Psychiatry; impressão 2024; o GPM o chama "2021")',
 'As diferenças bioenergéticas dos fibroblastos de pacientes com TDM persistem parcialmente em iNPC/iPS-neurônios, com alteração funcional neuronal associada.',[]),
('REF_KUFFNER_2020','32260327','Kuffner 2020','EC','BLOCO01',3,'human_experimental','bem_suportado',
 'fibroblastos dérmicos adultos (TDM × controles) — master GPM','regra fundadora 5 — compartimento fibroblasto',
 'Fibroblastos de pacientes com TDM exibem função mitocondrial prejudicada (respiração basal/máxima reduzidas, alterações do sistema OXPHOS).',[]),
('REF_MARQUES_2021','34066918','Marques 2021','EC','BLOCO01',4,'human_experimental','moderadamente_suportado',
 'fibroblastos de bipolar em fase inicial — master GPM','bipolar como fronteira; distúrbio mitocondrial precoce',
 'Em fibroblastos de bipolar em fase inicial: alterações de biogênese/dinâmica e potencial de membrana, depleção de ATP da CTE com estimulação de glicólise — distúrbio como evento precoce (entidade distinta da TDM).',[]),
('REF_CULLEN_2026','41776167','Cullen 2026','EC','BLOCO01',5,'human_clinical','moderadamente_suportado',
 'estudo humano (jovens adultos; ATP em cérebro — MRS — e sangue)','assinatura bioenergética de ATP da fadiga na TDM inicial',
 'Em adultos jovens com TDM, a bioenergética de ATP revela assinatura associada à fadiga visível no cérebro e no sangue, com menor capacidade de produção de ATP em PBMC sob desacoplamento — interpretada como mecanismo compensatório em estágio inicial.',[]),
('REF_EMMERZAAL_2020','32488052','Emmerzaal 2020','ML','BLOCO01',6,'preclinical_mechanistic','moderadamente_suportado',
 'modelo murino (gene-trap) com função prejudicada do complexo I','motor candidato da reatividade ao estresse — depressão-like (animal)',
 'Camundongos com função prejudicada do complexo I apresentam reatividade ao estresse alterada e reprogramação do metabolismo cerebral/aminoácido — o defeito do complexo I é motor candidato, não mero epifenômeno, em modelo.',[]),
('REF_BERGMAN_2016','27412728','Bergman 2016','OB','BLOCO01',7,'review','bem_suportado',
 'revisão (Can J Psychiatry)','OXPHOS na esquizofrenia — FRONTEIRA ILUSTRATIVA (camada C), sem seta "esquizofrenia → comprova depressão"',
 'Os déficits do sistema de fosforilação oxidativa na esquizofrenia revistos como patologia distinta sobre a mesma organela — ilustração de método, não evidência do eixo no humor.',[]),
# ================= BLOCO_01 §1.2 Dinâmica =================
('REF_OTERA_2013','23434681','Otera 2013','OB','BLOCO01',8,'review','bem_suportado',
 'revisão (BBA) — master GPM','mecânica da fissão dependente de DRP1',
 'Revisão da função e regulação da fissão mitocondrial (recrutamento/assembly de Drp1, modificações pós-traducionais, papel fisiopatológico).',[]),
('REF_CAO_2017','28114303','Cao 2017','OB','BLOCO01',9,'review','bem_suportado',
 'estudo estrutural (Nature) — master GPM','âncora estrutural da fusão (MFN1)',
 'Estruturas de MFN1 revelam dimerização dependente de nucleotídeo crítica para a fusão mitocondrial — base molecular do mecanismo de tethering.',[]),
('REF_CHANDHOK_2018','29068134','Chandhok 2018','OB','BLOCO01',10,'review','bem_suportado',
 'revisão de referência (Biol Rev) — master GPM','estrutura/função/regulação de MFN2',
 'Consolidação do conhecimento estrutural e funcional de MFN2 e sua regulação, com as consequências da expressão aberrante na doença.',[]),
('REF_FENG_2020','31760107','Feng 2020','OB','BLOCO01',11,'review','bem_suportado',
 'revisão (Pharmacol Res) — master GPM','DRP1: fissão, mitofagia e patologia',
 'DRP1 revisado como proteína crítica da fissão mitocondrial, com papel na mitofagia e na patobiologia.',[]),
('REF_YAPA_2021','33742459','Yapa 2021','OB','BLOCO01',12,'review','bem_suportado',
 'revisão (FEBS Lett) — master GPM','dinâmica mitocondrial na saúde e na doença',
 'A maquinaria da dinâmica mitocondrial (fissão/fusão/transporte) revista, com o desequilíbrio — não um dos polos — como motor da doença.',[]),
('REF_ZANFARDINO_2025','40149969','Zanfardino 2025','OB','BLOCO01',13,'review','bem_suportado',
 'revisão (Biomolecules) — master GPM','equilíbrio MFN2–OPA1; binário "fissão ruim/fusão boa" é falso',
 'Revisão do equilíbrio MFN2/OPA1 na dinâmica mitocondrial, homeostase celular e doença — reforça que a doença pode vir dos dois sentidos do equilíbrio.',[]),
('REF_LAGOS_2026','42248856','Lagos 2026','ML','BLOCO01',14,'preclinical_mechanistic','moderadamente_suportado',
 'estudo mecanístico de mutantes de MFN2 (Cell Death Dis; célula)','doença dos dois lados do equilíbrio fissão×fusão (mecânica; CMT2A = fronteira)',
 'Mutantes de MFN2 causadores de doença prejudicam a fissão por mecanismos distintos de desregulação de DRP1 — evidência mecanística de que o defeito não é umidirecional.',[]),
('REF_BURTE_2015','25486875','Burté 2015','OB','BLOCO01',15,'review','bem_suportado',
 'revisão (Nat Rev Neurol) — master GPM','dinâmica perturbada nas doenças neurodegenerativas — CAMADA C, fronteira ilustrativa',
 'Revisão clássica da dinâmica mitocondrial perturbada nas doenças neurodegenerativas — mecânica compartilhada da organela, proibida a extrapolação "Parkinson/Alzheimer → comprova depressão".',
 ['BURTÉ','Burté','BURTE','Burte']),
('REF_CARELLI_2015','25820230','Carelli 2015','EC','BLOCO01',16,'human_clinical','moderadamente_suportado',
 'série clínico-genética humana (Ann Neurol); mutações missense de OPA1','parkinsonismo/demência sindrômicos — CAMADA C, fronteira ilustrativa de mecânica',
 'Mutações missense de OPA1 associam-se a parkinsonismo sindrômico e demência — demonstra a centralidade humana da proteína, sem carregar evidência para o humor.',[]),
('REF_ALAIMO_2014','24632637','Alaimo 2014','ML','BLOCO01',17,'preclinical_mechanistic','moderadamente_suportado',
 'células astrogliais de rato + modelo (PLoS One); manganês','toxicologia/Parkinsonismo — CAMADA B mecânica, sem extrapolação ao humor',
 'Manganês desregula OPA-1/DRP-1 com fissão exacerbada e apoptose; inibir DRP-1 (Mdivi-1/siRNA) protege a rede mitocondrial — mecânica da dinâmica sob insulto.',[]),
('REF_XIE_2025','40668505','Xie 2025','ML','BLOCO01',18,'preclinical_mechanistic','moderadamente_suportado',
 'roedor com síndrome tipo-depressiva (Mol Neurobiol)','epigenética do eixo: acetilação de MFN2 (sinal emergente, animal)',
 'A acetilação elevada de MFN2 acompanha a disrupção da produção energética mitocondrial e a inflamação no modelo tipo-depressivo — elo epigenético-mitocondrial.',[]),
('REF_SCAINI_2017','28463235','Scaini 2017','EC','BLOCO01',19,'human_clinical','bem_suportado',
 'sangue periférico de pacientes com TDM (Transl Psychiatry)','via apoptótica e dinâmica da rede mitocondrial perturbadas (humano; distinto do vigente Scaini 2021)',
 'Na TDM, a via apoptótica e a dinâmica da rede mitocondrial estão perturbadas em mononucleares de sangue periférico — evidência humana de dinâmica/qualidade alteradas no compartimento periférico.',[]),
# ================= BLOCO_01 §1.5 Redox =================
('REF_PALMA_2024','38081963','Palma 2024','OB','BLOCO01',20,'review','bem_suportado',
 'revisão (Oncogene) — master GPM','regra fundadora 1: ROS é sinal fisiológico; "função ou disfunção?"',
 'A produção de ROS pelas mitocôndrias revisada do ângulo função × disfunção — base da formulação "desregulação da sinalização redox", nunca "ROS ruim".',[]),
('REF_NAPOLITANO_2021','34829696','Napolitano 2021','OB','BLOCO01',21,'review','bem_suportado',
 'revisão (Antioxidants) — master GPM','manejo mitocondrial das espécies reativas',
 'Sistematização do manejo mitocondrial dos ROS — fontes, alvos e defesas da organela.',[]),
('REF_ANGELOVA_2018','29292494','Angelova 2018','OB','BLOCO01',22,'review','bem_suportado',
 'revisão (FEBS Lett) — master GPM','mtROS no cérebro: da fisiologia à neurodegeneração',
 'O papel do ROS mitocondrial no cérebro revisado do fisiológico ao neurodegenerativo — reforça a leitura de sinal antes de dano.',[]),
('REF_STEFANATOS_2018','29106705','Stefanatos 2018','OB','BLOCO01',23,'review','moderadamente_suportado',
 'revisão (FEBS Lett) — master GPM','mtROS no cérebro em envelhecimento — CAMADA C contextual',
 'O papel do ROS mitocondrial no envelhecimento cerebral — contexto de dano cumulativo, não leitura do humor.',[]),
('REF_KOWALCZYK_2021','34948180','Kowalczyk 2021','OB','BLOCO01',24,'review','bem_suportado',
 'revisão (Int J Mol Sci) — master GPM','estresse oxidativo mitocondrial como fator causativo/alvo',
 'Revisão do estresse oxidativo mitocondrial como fator causativo e alvo terapêutico em doenças, com foco neuropsiquiátrico.',[]),
('REF_MORRIS_2020','32564227','Morris 2020','OB','BLOCO01',25,'review','bem_suportado',
 'revisão (Mol Biol Rep) — extra auditado','interplay estresse oxidativo × falha bioenergética',
 'A interação entre estresse oxidativo e falha bioenergética revisada nas condições neuropsiquiátricas — loop fonte/vítima da organela.',[]),
('REF_KIM_2019','30585734','Kim 2019','OB','BLOCO01',26,'review','bem_suportado',
 'revisão (Antioxid Redox Signal) — extra auditado','mitocôndria, metabolismo e redox em transtornos psiquiátricos',
 'Revisão do tripé mitocôndria–metabolismo–mecanismos redox nos transtornos psiquiátricos.',[]),
('REF_LIU_2025','40427494','Liu 2025','OB','BLOCO01',27,'review','emergente',
 'revisão (Antioxidants) — extra auditado','eixo ferroptose–mitocôndria na depressão — loop feedforward (emergente)',
 'O eixo ferroptose–mitocôndria na depressão: desmontando o loop feedforward entre lipoperoxidação e disfunção da organela — leitura recente, ainda emergente.',
 ['LIUX','Liu X','LiuX2025']),
# ================= BLOCO_01 §1.6 Mitofagia/UPRmt =================
('REF_POOLE_2008','18230723','Poole 2008','ML','BLOCO01',28,'preclinical_mechanistic','bem_suportado',
 'modelo experimental (PNAS) — master GPM','âncora clássica PINK1/Parkin × morfologia',
 'A via PINK1/Parkin regula a morfologia mitocondrial — âncora clássica do controle de qualidade.',[]),
('REF_LUTZ_2009','19546216','Lutz 2009','ML','BLOCO01',29,'preclinical_mechanistic','bem_suportado',
 'modelo experimental (J Biol Chem) — master GPM','perda de parkin/PINK1 → fragmentação DRP1-dependente',
 'A perda de função de parkin ou PINK1 aumenta a fragmentação mitocondrial dependente de DRP1.',[]),
('REF_YU_2011','21613270','Yu 2011','ML','BLOCO01',30,'preclinical_mechanistic','bem_suportado',
 'neurônios de mamífero (Hum Mol Genet) — master GPM','PINK1/Parkin × dinâmica e função em neurônio',
 'A via PINK1/Parkin regula a dinâmica e a função mitocondrial em neurônios de mamífero.',[]),
('REF_ULECIAMORON_2025','40410878','Ulecia-Morón 2025','ML','BLOCO01',31,'preclinical_mechanistic','moderadamente_suportado',
 'estresse crônico leve em rato (J Transl Med); córtex frontal','estresse → disrupção de mitofagia/status mitocondrial (animal)',
 'O estresse crônico leve disrompe a mitofagia e o status mitocondrial no córtex frontal de rato — elo direto estresse × controle de qualidade.',
 ['ULECIA-MORÓN','Ulecia-Morón','ULECIAMORON','Uleciamoron','MORÓN','Morón','MORON','Moron']),
('REF_HOFSTRA_2024','38800537','Hofstra 2024','ML','BLOCO01',32,'preclinical_mechanistic','emergente',
 'cross-espécies: separação materna em camundongo + transcriptoma humano público (Neurobiol Stress)','âncora UPRmt/ISR cross-espécies — emergente, sem estudo humano dedicado [G1]',
 'Análise cross-espécies revela assinatura compartilhada de resposta de estresse mitocondrial no hipocampo (OXPHOS e dobramento proteico/UPRmt) entre camundongo com estresse precoce e transcriptoma de pacientes deprimidos — emergente.',[]),
# ================= BLOCO_01 §1.7 DAMP/inflamação =================
('REF_PATERGNANI_2021','33672477','Patergnani 2021','OB','BLOCO01',33,'review','bem_suportado',
 'revisão (Biomedicines) — master GPM','"mito-inflamação" como ator da doença',
 'Estresse oxidativo mitocondrial e "mito-inflamação" revisados como atores na doença — archteipo do acoplamento organela-imunidade.',[]),
('REF_VISENTIN_2020','32351669','Visentin 2020','OB','BLOCO01',34,'review','bem_suportado',
 'revisão (Oxid Med Cell Longev) — master GPM','resposta inflamatório-mitocondrial na depressão maior',
 'A resposta inflamatório-mitocondrial como alvo na depressão maior — evidência corrente revista.',[]),
('REF_CULMSEE_2018','30687139','Culmsee 2018','OB','BLOCO01',35,'review','bem_suportado',
 'revisão (Front Psychiatry) — master GPM','mitocôndria–micróglia–imune nos transtornos afetivos',
 'Como mitocôndrias, micróglia e sistema imune se ligam nos transtornos afetivos — revisão do tripé.',[]),
('REF_CAI_2024','38857809','Cai 2024','OB','BLOCO01',36,'review','bem_suportado',
 'revisão (Neurobiol Dis) — master GPM','DRP1 × neuroinflamação: a dinâmica alimenta a imunidade',
 'A desregulação de DRP1 como nó entre dinâmica mitocondrial e neuroinflamação, revista nas doenças neurológicas com leitura mecanística para os afetivos.',
 ['CAIP','Cai P']),
# ================= BLOCO_01 §1.8 Estresse/social =================
('REF_DONG_2023','37985735','Dong 2023','ML','BLOCO01',37,'preclinical_mechanistic','bem_suportado',
 'camundongo; estresse crônico (Nat Metab)','regra fundadora 6: causalidade experimental é âncora (estresse → DRP1 → fissão mPFC → comportamento; inibir DRP1 atenua)',
 'O estresse crônico promove fissão mitocondrial no córtex pré-frontal medial via DRP1, impondo ônus metabólico neuronal que aumenta a suscetibilidade ao estresse; a inibição de DRP1 atenua o fenótipo — causalidade em animal, com [EXTRAPOLAÇÃO POR ANALOGIA].',[]),
('REF_XIE_2020','32045672','Xie 2020','ML','BLOCO01',38,'preclinical_mechanistic','moderadamente_suportado',
 'corticosterona crônica em roedor (J Steroid Biochem Mol Biol)','hormônio de estresse → comportamento tipo-depressivo + metabolismo energético mitocondrial',
 'O corticosterona crônico induz comportamento tipo-depressivo acompanhado de disrupção do metabolismo energético mitocondrial em roedor — transdução endócrino-mitocondrial.',
 ['XIE2020']),
('REF_HOLLIS_2015','26621716','Hollis 2015','ML','BLOCO01',39,'preclinical_mechanistic','bem_suportado',
 'ratos; hierarquia social (PNAS) — master GPM','regra fundadora 9: modelo de ansiedade social é âncora legítima',
 'A função mitocondrial no núcleo accumbens liga a ansiedade-traço à subordinação social em ratos — a ansiedade influencia diretamente a hierarquia, com mediação mitocondrial.',[]),
('REF_WATANABE_2022','36252817','Watanabe 2022','ML','BLOCO01',40,'preclinical_mechanistic','moderadamente_suportado',
 'isolamento social em camundongo (Neurochem Int)','isolamento social → disfunção de succinato-desidrogenase',
 'O isolamento social induz disfunção da succinato-desidrogenase (SDH) em camundongos ansiosos — elo TCA × comportamento social.',[]),
('REF_ROSENBERG_2023','37563104','Rosenberg 2023','ML','BLOCO01',41,'preclinical_mechanistic','bem_suportado',
 'camundongos; escala cerebral ampla (Nat Commun)','diversidade/organização de rede mitocondrial prediz ansiedade-like',
 'A diversidade e a organização de rede das mitocôndrias cerebrais em escala ampla predizem comportamento tipo-ansioso em camundongos.',[]),
# ================= BLOCO_01 §1.9 MAO =================
('REF_KALIMON_2023','36841465','Kalimon 2023','ML','BLOCO01',42,'preclinical_mechanistic','moderadamente_suportado',
 'mitocôndrias isoladas do córtex de camundongo (Exp Neurol)','MAO-A (membrana mitocondrial externa) × bioenergética — ponte B4',
 'A inibição seletiva de MAO-A (não MAO-B) aumenta o consumo de oxigênio acoplado ao complexo I em mitocôndrias isoladas do córtex de camundongo — a enzima monoaminérgica modula a bioenergética local.',[]),
# ================= BLOCO_01 §1.10 Fronteira/integradores =================
('REF_JAVANI_2022','35065970','Javani 2022','ML','BLOCO01',43,'preclinical_mechanistic','emergente',
 'transplante ICV de mitocôndrias; rato idoso sob estresse crônico (Mech Ageing Dev)','regra fundadora 7: terapia só como sinal — transplante mitocondrial (animal)',
 'O transplante intracerebroventricular de mitocôndrias isoladas de cérebro jovem melhorou comportamentos tipo-depressivos em ratos idosos sob estresse crônico leve — sinal experimental apenas.',[]),
('REF_MAFIKANDI_2025','39333279','Mafikandi 2025','ML','BLOCO01',44,'preclinical_mechanistic','emergente',
 'administração intranasal de mitocôndrias; camundongo (estresse de contenção)','regra fundadora 7: via intranasal — sinal experimental apenas',
 'A administração nasal de mitocôndrias aliviou comportamentos tipo-depressivos/ansiosos e marcadores neuroinflamatório-oxidativos em camundongos sob estresse de contenção — sinal pré-clínico.',[]),
('REF_TIAN_2026','41848740','Tian 2026','ML','BLOCO01',45,'preclinical_mechanistic','emergente',
 'ratos; astragalosídeo IV; eixo ROS–Nrf2/Keap1 (Antioxid Redox Signal)','fitoterápico como sinal mecanístico redox/energia — nunca recomendação',
 'O astragalosídeo IV conferiu eficácia profilática em modelo de depressão, revertendo a desregulação redox e restaurando indicadores de metabolismo energético via eixo ROS–Nrf2/Keap1 — sinal mecanístico animal, não recomendação.',[]),
('REF_GIMENEZPALOMO_2021','34295268','Giménez-Palomo 2021','OB','BLOCO01',46,'review','bem_suportado',
 'revisão integradora (Front Psychiatry) — extra auditado (≠ vigente 2024 fase maníaca)','o papel das mitocôndrias nos transtornos de humor: fisiologia → patofisiologia',
 'Revisão do papel das mitocôndrias nos transtornos do humor, da fisiologia à patofisiologia e perspectivas terapêuticas.',
 ['GIMÉNEZ-PALOMO','Giménez-Palomo','PALOMO','Palomo']),
('REF_JIANG_2024','38334212','Jiang 2024','OB','BLOCO01',47,'review','bem_suportado',
 'revisão (CNS Neurosci Ther) — extra auditado','disfunção do metabolismo energético mitocondrial na depressão',
 'A disfunção do metabolismo energético mitocondrial na depressão — revisão do campo.',[]),
('REF_BUTTIKER_2022','36686690','Büttiker 2022','OB','BLOCO01',48,'review','bem_suportado',
 'revisão (Front Pharmacol) — extra auditado','processos mitocondriais disfuncionais × perturbações energéticas cerebrais',
 'Os processos mitocondriais disfuncionais como contribuintes das perturbações energéticas no cérebro e dos sintomas neuropsiquiátricos — revisão.',
 ['BÜTTIKER','Büttiker','BUTTIKER','Buttiker']),
('REF_KOLAR_2021','34098028','Kolár 2021','OB','BLOCO01',49,'review','moderadamente_suportado',
 'mini-revisão (Neurosci Lett) — extra auditado','metabolismo energético cerebral em MODELOS ANIMAIS de depressão',
 'Mini-revisão do metabolismo energético cerebral e seu papel nos modelos animais de depressão — qualificador do que é evidência de modelo.',
 ['KOLÁR','Kolár','KOLAR','Kolar']),
('REF_LUPTAK_2019','31755286','Ľupták 2019','OB','BLOCO01',50,'review','bem_suportado',
 'revisão (Physiol Res) — extra auditado','âncora do confundedor medicação: estabilizadores de humor têm efeitos mitocondriais próprios',
 'O papel da mitocôndria e o efeito dos estabilizadores de humor sobre a função mitocondrial — a medicação é confundidora de primeira ordem na leitura dos marcadores.',
 ['ĽUPTÁK','Ľupták','LUPTAK','Luptak']),
('REF_KARABATSIAKIS_2020','32647150','Karabatsiakis 2020','OB','BLOCO01',51,'review','moderadamente_suportado',
 'revisão/perspectiva (Transl Psychiatry) — master GPM','bioenergética × ECT; origem do conceito "Mito-Mood" — hipótese estruturante [G1] (regra 11)',
 'Depressão, bioenergética mitocondrial e eletroconvulsoterapia: propõe a função mitocondrial como biomarcador candidato de diagnóstico/resposta em TDM e estrutura o conceito "Mito-Mood" — hipótese [G1], não fato.',[]),
# ================= BLOCO_02 §2.5 mtDNA (quatro lentes) =================
('REF_CAI_2015','26687620','Cai 2015','EC','BLOCO02',1,'human_clinical','bem_suportado',
 'coorte genética (CONVERGE; 10,4 mil mulheres chinesas) + paradigma murino (Curr Biol)','controle genético nuclear do mtDNA; heteroplasmia ↑ na TDM por estresse',
 'Loci nucleares em TFAM e CDK6 controlam a quantidade de mtDNA; mulheres com TDM têm taxas maiores de heteroplasmia, com paradigma em camundongo indicando o estresse como causa provável.',
 ['CAIN','Cai N']),
('REF_KASAHARA_2018','29102411','Kasahara 2018','OB','BLOCO02',2,'review','bem_suportado',
 'revisão de método (Biol Psychiatry) — extra auditado','o que a análise do mtDNA pode dizer sobre os transtornos de humor',
 'Revisão do que décadas de análise de mtDNA (e de genes nucleares mitocondriais) ensinam sobre transtornos de humor — com os limites e desafios do método.',[]),
('REF_LINDQVIST_2018','29453441','Lindqvist 2018','EC','BLOCO02',3,'human_clinical','bem_suportado',
 'estudo humano TDM (Neuropsychopharmacology); duas frações medidas','regra fundadora 2: ccf-mtDNA ↑ SEM mudança no CN leucocitário — proibido "MDD aumenta mtDNA"',
 'Na TDM, o ccf-mtDNA circulante está elevado sem alteração do copy number leucocitário — as duas frações refletem processos celulares distintos; o ccf-mtDNA pode refletir aspectos da fisiopatologia e da resposta a ISRS.',[]),
('REF_CHUNG_2019','31639552','Chung 2019','EC','BLOCO02',4,'human_clinical','bem_suportado',
 '118 TDM × 116 controles; sangue periférico (Psychiatry Res)','mtDNA-CN elevado na TDM + hipometilação do promotor de PGC1α',
 'Pacientes com TDM apresentam mtDNA copy number mais alto e menor metilação do promotor de PGC1α; o CN associa-se negativamente a idade, agitação psicomotora e sintomas somáticos.',[]),
('REF_CZARNY_2020','31081430','Czarny 2020','EC','BLOCO02',5,'human_clinical','bem_suportado',
 'PBMC; 25 deprimidos × 60 controles; insulto H2O2 ex vivo (World J Biol Psychiatry)','reparo e degradação do mtDNA prejudicados na depressão',
 'PBMCs de pacientes deprimidos acumulam lesões de mtDNA após estresse oxidativo ex vivo, com reparo e degradação prejudicados — primeira demonstração do defeito de manutenção.',[]),
('REF_CZARNY_2023','37834200','Czarny 2023','EC','BLOCO02',6,'human_clinical','moderadamente_suportado',
 'associação genética; SNPs de genes de estabilidade do mtDNA (Int J Mol Sci)','variantes dos genes de manutenção do mtDNA × início/desfecho',
 'SNPs nos genes que mantêm a estabilidade do mtDNA (replicação/reparo/degradação) associam-se à depressão e podem influenciar o início e o desfecho do tratamento.',[]),
('REF_RYAN_2023','36216200','Ryan 2023','EC','BLOCO02',7,'human_clinical','bem_suportado',
 'sangue total; 100 pacientes medicados com depressão (Prog Neuropsychopharmacol Biol Psychiatry)','mtDNAcn elevado na depressão + relação com resposta à ECT (≠ vigente Ryan 2019)',
 'O mtDNAcn está elevado no sangue de pacientes com depressão medicados e relaciona-se à resposta ao tratamento — sem tradução garantida para a função mitocondrial.',[]),
('REF_WANG_2017','28647451','Wang 2017','EC','BLOCO02',8,'human_clinical','bem_suportado',
 '179 pacientes (atenção primária) × 320 controles (Eur Neuropsychopharmacol)','mtDNA-CN maior em depressão/ansiedade/ajustamento; associa-se a gravidade e resposta',
 'O mtDNA copy number está significativamente mais alto em pacientes com depressão, ansiedade e transtornos de estresse/ajustamento, associando-se à gravidade basal e à resposta após 8 semanas de tratamento.',[]),
('REF_CHANG_2015','25946463','Chang 2015','EC','BLOCO02',9,'human_clinical','moderadamente_suportado',
 '40 TDM clinicamente estáveis × 70 controles (PLoS One)','CN leucocitário MENOR + dano oxidativo do mtDNA MAIOR (direções cruzadas)',
 'Em pacientes clinicamente estáveis, o CN leucocitário do mtDNA é significativamente menor e o dano oxidativo significativamente maior do que nos controles — ilustra a heterogeneidade direcional do CN.',[]),
('REF_CEYLAN_2023','38161720','Ceylan 2023','EC','BLOCO02',10,'human_clinical','moderadamente_suportado',
 'TDM × bipolar × controles; remissão 8 semanas (Front Psychiatry)','metilação do D-loop ↑ na TDM (CN/oxidação comparáveis); CN e metilação caem na remissão (≠ vigente Ceylan 2024)',
 'A metilação do D-loop está aumentada na TDM versus bipolar e controles, com mtDNA-cn e oxidação comparáveis; CN relative e metilação caem na remissão — distintas modificações do mtDNA entre condições.',[]),
('REF_TYMOFIYEVA_2018','29500956','Tymofiyeva 2018','EC','BLOCO02',11,'human_clinical','moderadamente_suportado',
 'adolescentes; mtDNA-cn + ressonância (J Affect Disord)','mtDNA-cn alto × sintomas ansiosos × conectividade fronto-ocipital',
 'Em adolescentes, o mtDNA-cn aumentado associa-se a mais sintomas de ansiedade e a menor conectividade estrutural fronto-ocipital.',[]),
('REF_BECK_2025','40517524','Beck 2025','EC','BLOCO02',12,'human_clinical','moderadamente_suportado',
 'estresse precoce (ELS) com/sem condição psiquiátrica (Psychoneuroendocrinology)','ELS só eleva mtDNAcn quando há sintomatologia psiquiátrica',
 'O mtDNAcn está aumentado em indivíduos com estresse precoce E condição psiquiátrica, mas não naqueles com ELS sem psicopatologia — o efeito do estresse aparece apenas com sintomatologia.',[]),
('REF_LIU_2023','37344456','Liu 2023','EC','BLOCO02',13,'human_clinical','bem_suportado',
 'MiWAS no UK Biobank (Transl Psychiatry); N≈72–81 mil por desfecho','mtDNA × CRP: interações para ansiedade/depressão — ponte B1',
 'Estudo de associação mitocondrial-ampla identifica SNPs do mtDNA associados a ansiedade/depressão e interações mtDNA×PCR significativas — documenta o acoplamento mitocôndria–inflamação em escala populacional.',
 ['LIUL','Liu L','LiuL2023']),
('REF_ROLLINS_2009','19290059','Rollins 2009','EC','BLOCO02',14,'human_clinical','moderadamente_suportado',
 'tecido cerebral pós-morte (PLoS One)','variantes de mtDNA em esquizofrenia/bipolar/TDM; pH × haplogrupo',
 'Variantes de sequência do mtDNA descritas em cérebro pós-morte através de esquizofrenia, bipolar e TDM, com associação entre pH cerebral e super-haplogrupo — exploração, não marcador fechado.',[]),
('REF_SEQUEIRA_2015','26011537','Sequeira 2015','EC','BLOCO02',15,'human_clinical','moderadamente_suportado',
 'tecido cerebral pós-morte; sequenciamento (PLoS One)','mutações somáticas de mtDNA mais frequentes em casos selecionados',
 'Mutações somáticas de mtDNA em tecido cerebral observadas em maior frequência em casos selecionados de transtornos psiquiátricos — indicadores de instabilidade genômica mitocondrial.',[]),
('REF_GUPTA_2023','37587338','Gupta 2023','EC','BLOCO02',16,'human_clinical','bem_suportado',
 'genética populacional em larga escala (Nature)','o genoma nuclear molda CN e dinâmica de heteroplasmia',
 'A variação comum do genoma nuclear exerce controle genético sobre a abundância de mtDNA e a dinâmica da heteroplasmia na população humana.',[]),
('REF_KLEIN_2021','34742335','Klein 2021','EC','BLOCO02',17,'human_clinical','moderadamente_suportado',
 'cérebro humano envelhecido; patologias da idade (Mol Neurodegener)','CAMADA C contextual: recalibração do mtDNA por patologia etária; mutações puntiformes SEM papel maior',
 'No cérebro envelhecido, o mtDNAcn recalibra-se conforme a carga de patologias etárias; mutações puntiformes/heteroplasmia não se associam à patogênese — contextual, não leitura do humor.',[]),
('REF_WEI_2017','28153046','Wei 2017','EC','BLOCO02',18,'human_clinical','moderadamente_suportado',
 '1.363 amostras doença/controle (Acta Neuropathol Commun)','NEG de fronteira: variantes puntiformes do mtDNA sem papel maior nas neurodegenerações; níveis merecem investigação',
 'Em 1.363 amostras, variantes puntiformes do mtDNA não mostram papel maior na patogênese das doenças neurodegenerativas, enquanto os níveis de mtDNA (reduzidos em DA/CJD) merecem investigação — inventário negativo de fronteira.',[]),
('REF_TRANAH_2018','29984425','Tranah 2018','EC','BLOCO02',19,'human_clinical','moderadamente_suportado',
 'homens idosos; plaqueta (Int J Geriatr Psychiatry)','heteroplasmia m.13514G>A (complexo I) × sintomas depressivos',
 'A heteroplasmia do mtDNA no sítio m.13514G>A do complexo I associa-se a sintomas depressivos em homens idosos — fator de risco biológico candidato.',[]),
('REF_YIN_2026','40915505','Yin 2026','EC','BLOCO02',20,'human_clinical','moderadamente_suportado',
 'sequenciamento completo do mtDNA; TDM (J Affect Disord)','carga de mutações + mutações funcionais específicas; haplótipo protetor candidato',
 'A análise completa da sequência do mtDNA na TDM aponta que o risco não se resume à carga mutacional — mutações funcionais específicas e um haplótipo protetor candidato (B4) se destacam.',[]),
('REF_ZONG_2026','41792945','Zong 2026','EC','BLOCO02',21,'human_clinical','emergente',
 'pacientes chineses com lúpus eritematoso sistêmico; dois estágios (Int J Rheum Dis)','FRONTEIRA contextual: depressão/ansiedade EM comorbidade de doença sistêmica',
 'Variantes genéticas do mtDNA associam-se a depressão e ansiedade em pacientes com lúpus, com alterações concordantes de ROS, IL-6 e ATP no grupo variante — comorbidade em doença sistêmica, não TDM primária.',[]),
('REF_VALIENTEPALLEJA_2022','35085849','Valiente-Pallejà 2022','OB','BLOCO02',22,'review','bem_suportado',
 'sumário/revisão abrangente; cérebro humano pós-morte (EBioMedicine)','mapa das alterações de mtDNA no cérebro pós-morte',
 'Revisão abrangente das alterações do mtDNA no cérebro humano pós-morte — tipo de alteração, regiões, níveis de heteroplasmia e relação com fenótipos e envelhecimento.',
 ['VALIENTE-PALLEJÀ','Valiente-Pallejà','PALLEJÀ','Pallejà','VALIENTEPALLEJA','Valientepalleja']),
('REF_XUE_2026','41634133','Xue 2026','EC','BLOCO02',23,'human_clinical','bem_suportado',
 'maiores GWAS disponíveis; arquitetura compartilhada (Mol Psychiatry)','arquitetura genética compartilhada mtDNA-CN × transtornos psiquiátricos — ≠ causalidade (regra 3)',
 'Mapeamento da arquitetura genética compartilhada entre mtDNA-CN e condições psiquiátricas: sobreposição global, loci compartilhados e vias ubiquitina/desenvolvimento com sub-regulação em regiões cerebrais-chave.',[]),
('REF_LU_2024','39197553','Lu 2024','EC','BLOCO02',24,'human_clinical','bem_suportado',
 'randomização mendeliana bidirecional de duas amostras (J Affect Disord)','regra fundadora 3: MR NULO para mtDNA-CN × MDD/ansiedade/bipolar/esquizofrenia/TOC e reversos; briefing dizia "não resolvido" — é 39197553',
 'A MR bidirecional NÃO sustentou associação causal entre mtDNA-CN no sangue e MDD, ansiedade, bipolar, esquizofrenia ou TOC (nem vias reversas); sustentou sinal potencial apenas para TEA — fora do escopo. Qualificador interpretativo, não refutação da disfunção.',
 ['LUY','Lu Y']),
('REF_FERNANDEZPECH_2026','41921723','Fernández-Pech 2026','OB','BLOCO02',25,'review','bem_suportado',
 'revisão sistemática PRISMA 2020; ccf-mtDNA em psiquiatria (Neurosci Biobehav Rev)','SR de ccf-mtDNA: sinal mais consistente em transtornos depressivos; heterogeneidade/transversalidade advertidas',
 'SR do ccf-mtDNA em bipolar/depressão/esquizofrenia: elevação mais consistente nos transtornos depressivos (sobretudo sem medicação e na depressão tardia), heterogênea no bipolar, nula em geral na esquizofrenia — com advertência de heterogeneidade metodológica, amostras pequenas e desenhos transversais.',
 ['FERNÁNDEZ-PECH','Fernández-Pech','FERNANDEZPECH','Fernandezpech','PECH','Pech']),
]

# ---- consistência estrutural ----
if __name__ == '__main__' or True:
    assert len(D) == 76, len(D)
    assert len({d[0] for d in D}) == 76, 'rid duplicado'
    assert len({d[1] for d in D}) == 76, 'pmid duplicado'
    assert len({d[2] for d in D}) == 76, 'prosa duplicada'
    VIG = {'REF_ALCOCERGOMEZ_2014','REF_ANDREAZZA_2010','REF_BANSAL_2016','REF_BENSHACHAR_2008',
     'REF_BODENSTEIN_2019','REF_CALARCO_2024','REF_CASARIL_2021','REF_CEYLAN_2024','REF_CIUBUCBATCU_2024',
     'REF_CLAY_2011','REF_DENG_2024','REF_EINAT_2005','REF_FANIBUNDA_2019','REF_FERNSTROM_2021',
     'REF_FILIOU_2019','REF_FILIPOVIC_2025','REF_GEBARA_2020','REF_GIMENEZPALOMO_2024','REF_HOLPER_2019',
     'REF_HROUDOVA_2013','REF_KARABATSIAKIS_2014','REF_KATO_2000','REF_KHAN_2023','REF_KONRADI_2004',
     'REF_KUANG_2018','REF_MADRIGAL_2001','REF_MISIEWICZ_2019','REF_PAPAGEORGIOU_2024','REF_PICARD_2018',
     'REF_PICARD_2021','REF_RYAN_2019','REF_SCAINI_2021','REF_TORRELL_2013','REF_TRUMPFF_2021','REF_VERBAL_2026'}
    assert not ({d[0] for d in D} & VIG), 'colisão com vigente'
    TAG2EROLE = {'OB':'review','ML':'preclinical_mechanistic'}
    for d in D:
        assert d[3] in ('OB','EC','ML')
        assert d[6] in ('review','human_clinical','human_experimental','preclinical_mechanistic')
        assert d[7] in ('bem_suportado','moderadamente_suportado','emergente')
# Rótulos para as listras-resumo e o apêndice (SobrenomeAno_tema[TAG])
ROTULO = {
'REF_ALLEN_2018':'Allen2018_mitochondria_mood[OB]','REF_TRIEBELHORN_2024':'Triebelhorn2024_iPSC_bioenergetica[EC]',
'REF_KUFFNER_2020':'Kuffner2020_fibroblasto_TDM[EC]','REF_MARQUES_2021':'Marques2021_fibroblasto_bipolar[EC]',
'REF_CULLEN_2026':'Cullen2026_ATP_fadiga[EC]','REF_EMMERZAAL_2020':'Emmerzaal2020_complexoI[ML]',
'REF_BERGMAN_2016':'Bergman2016_OXPHOS_esq_fronteira[OB]','REF_OTERA_2013':'Otera2013_fissao[OB]',
'REF_CAO_2017':'Cao2017_MFN1_estrutura[OB]','REF_CHANDHOK_2018':'Chandhok2018_MFN2_revisao[OB]',
'REF_FENG_2020':'Feng2020_DRP1[OB]','REF_YAPA_2021':'Yapa2021_dinamica[OB]',
'REF_ZANFARDINO_2025':'Zanfardino2025_MFN2_OPA1[OB]','REF_LAGOS_2026':'Lagos2026_MFN2_mutantes[ML]',
'REF_BURTE_2015':'Burte2015_dinamica_neurodegen_front[OB]','REF_CARELLI_2015':'Carelli2015_OPA1_fronteira[EC]',
'REF_ALAIMO_2014':'Alaimo2014_manganes_OPA1_DRP1[ML]','REF_XIE_2025':'Xie2025_MFN2_acetilacao[ML]',
'REF_SCAINI_2017':'Scaini2017_rede_mitocondrial[EC]','REF_PALMA_2024':'Palma2024_ROS_funcao_disf[OB]',
'REF_NAPOLITANO_2021':'Napolitano2021_ROS_manejo[OB]','REF_ANGELOVA_2018':'Angelova2018_mtROS_cerebro[OB]',
'REF_STEFANATOS_2018':'Stefanatos2018_mtROS_envelhec[OB]','REF_KOWALCZYK_2021':'Kowalczyk2021_EO_mitocondrial[OB]',
'REF_MORRIS_2020':'Morris2020_EO_bioenergetica[OB]','REF_KIM_2019':'Kim2019_redox_psiquiatria[OB]',
'REF_LIU_2025':'Liu2025_ferroptose_eixo[OB]','REF_POOLE_2008':'Poole2008_PINK1_Parkin[ML]',
'REF_LUTZ_2009':'Lutz2009_parkin_PINK1_DRP1[ML]','REF_YU_2011':'Yu2011_PINK1_neuronio[ML]',
'REF_ULECIAMORON_2025':'UleciaMoron2025_mitofagia_estresse[ML]','REF_HOFSTRA_2024':'Hofstra2024_UPRmt_crossspecies[ML]',
'REF_PATERGNANI_2021':'Patergnani2021_mito_inflamacao[OB]','REF_VISENTIN_2020':'Visentin2020_inflam_mitocondrial[OB]',
'REF_CULMSEE_2018':'Culmsee2018_microglia_imune[OB]','REF_CAI_2024':'Cai2024_Drp1_neuroinflamacao[OB]',
'REF_DONG_2023':'Dong2023_DRP1_mPFC[ML]','REF_XIE_2020':'Xie2020_corticosterona_energia[ML]',
'REF_HOLLIS_2015':'Hollis2015_NAc_subordinacao[ML]','REF_WATANABE_2022':'Watanabe2022_SDH_isolamento[ML]',
'REF_ROSENBERG_2023':'Rosenberg2023_rede_ansiedade[ML]','REF_KALIMON_2023':'Kalimon2023_MAOA_respiracao[ML]',
'REF_JAVANI_2022':'Javani2022_transplante_mitocondrial[ML]','REF_MAFIKANDI_2025':'Mafikandi2025_mitocondria_intranasal[ML]',
'REF_TIAN_2026':'Tian2026_astragalosideo_Nrf2[ML]','REF_GIMENEZPALOMO_2021':'GimenezPalomo2021_mood_revisao[OB]',
'REF_JIANG_2024':'Jiang2024_depressao_energia[OB]','REF_BUTTIKER_2022':'Buttiker2022_processos_energia[OB]',
'REF_KOLAR_2021':'Kolar2021_energia_modelos[OB]','REF_LUPTAK_2019':'Luptak2019_estabilizadores_mito[OB]',
'REF_KARABATSIAKIS_2020':'Karabatsiakis2020_ECT_bioenergetica[OB]','REF_CAI_2015':'Cai2015_TFAM_CDK6_heteroplasmia[EC]',
'REF_KASAHARA_2018':'Kasahara2018_mtDNA_metodo[OB]','REF_LINDQVIST_2018':'Lindqvist2018_ccf_mtDNA[EC]',
'REF_CHUNG_2019':'Chung2019_mtDNAcn_TDM[EC]','REF_CZARNY_2020':'Czarny2020_reparo_mtDNA[EC]',
'REF_CZARNY_2023':'Czarny2023_SNP_mtDNA[EC]','REF_RYAN_2023':'Ryan2023_mtDNAcn_ECT[EC]',
'REF_WANG_2017':'Wang2017_mtDNAcn_sintomas[EC]','REF_CHANG_2015':'Chang2015_mtDNAcn_menor_dano[EC]',
'REF_CEYLAN_2023':'Ceylan2023_Dloop_metilacao[EC]','REF_TYMOFIYEVA_2018':'Tymofiyeva2018_mtDNA_adolescente[EC]',
'REF_BECK_2025':'Beck2025_ELS_mtDNAcn[EC]','REF_LIU_2023':'Liu2023_MiWAS_mtDNAxCRP[EC]',
'REF_ROLLINS_2009':'Rollins2009_variantes_postmortem[EC]','REF_SEQUEIRA_2015':'Sequeira2015_mutacoes_cerebro[EC]',
'REF_GUPTA_2023':'Gupta2023_controle_nuclear_mtDNA[EC]','REF_KLEIN_2021':'Klein2021_mtDNA_cerebro_idoso_front[EC]',
'REF_WEI_2017':'Wei2017_variantes_nulo_front[EC]','REF_TRANAH_2018':'Tranah2018_heteroplasmia_depressao[EC]',
'REF_YIN_2026':'Yin2026_sequencia_mtDNA_TDM[EC]','REF_ZONG_2026':'Zong2026_mtDNA_LES_fronteira[EC]',
'REF_VALIENTEPALLEJA_2022':'ValientePalleja2022_postmortem_revisao[OB]','REF_XUE_2026':'Xue2026_genetica_compartilhada[EC]',
'REF_LU_2024':'Lu2024_MR_nulo[EC]','REF_FERNANDEZPECH_2026':'FernandezPech2026_ccf_SR[OB]',
}
assert len(ROTULO) == 76 and set(ROTULO) == {d[0] for d in D}
